/**
 * Represents the metadata of a Kubernetes object.
 * Based on the Kubernetes API v1.23 ObjectMeta specification.
 *
 * @see {@link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#objectmeta-v1-meta | Kubernetes ObjectMeta API Reference}
 */
export interface KubernetesObjectMetaV1 {
  /**
   * The name of the object. Must be unique within a namespace.
   */
  name: string;

  /**
   * The namespace in which the object exists.
   * Can be undefined for cluster-scoped resources.
   */
  namespace?: string;

  /**
   * A URL representing this object. Populated by the system.
   */
  selfLink?: string;

  /**
   * A unique identifier for the object. Generated by the system.
   */
  uid?: string;

  /**
   * An opaque value that represents the internal version of this object.
   * Used for optimistic concurrency control and watch operations.
   */
  resourceVersion?: string;

  /**
   * A sequence number representing a specific generation of the desired state.
   * Populated by the system. Read-only.
   */
  generation?: number;

  /**
   * The timestamp when the object was created.
   * Format: RFC3339 date-time string.
   */
  creationTimestamp?: string;

  /**
   * The timestamp when the object was marked for deletion.
   * Only present if the object is being deleted.
   * Format: RFC3339 date-time string.
   */
  deletionTimestamp?: string;

  /**
   * The grace period in seconds before the object will be permanently deleted.
   * Only present if the object is being deleted.
   */
  deletionGracePeriodSeconds?: number;

  /**
   * Map of string keys and values that can be used to organize and categorize objects.
   */
  labels?: Record<string, string>;

  /**
   * Map of string keys and values that can be used to store arbitrary metadata.
   */
  annotations?: Record<string, string>;

  /**
   * List of objects that own this object.
   * Used for garbage collection and cascading deletions.
   */
  ownerReferences?: OwnerReference[];

  /**
   * List of finalizers that must be executed before the object can be deleted.
   */
  finalizers?: string[];

  /**
   * The name of the cluster where the object exists.
   * Only present for objects in a cluster.
   */
  clusterName?: string;

  /**
   * ManagedFields maps workflow-id and version to the set of fields
   * that are managed by that workflow.
   */
  managedFields?: ManagedField[];
}

/**
 * Represents a reference to another Kubernetes object that owns this object.
 */
interface OwnerReference {
  /**
   * The API version of the owner object.
   */
  apiVersion: string;

  /**
   * The kind of the owner object.
   */
  kind: string;

  /**
   * The name of the owner object.
   */
  name: string;

  /**
   * The UID of the owner object.
   */
  uid: string;

  /**
   * If true, this reference points to the managing controller.
   */
  controller: boolean;

  /**
   * If true, and the owner has the "foregroundDeletion" finalizer,
   * then the owner cannot be deleted from the key-value store until
   * this reference is removed.
   */
  blockOwnerDeletion?: boolean;
}

/**
 * Represents a managed field entry in the object metadata.
 */
interface ManagedField {
  /**
   * The API version of the field manager.
   */
  apiVersion: string;

  /**
   * The type of fields being managed.
   */
  fieldsType: string;

  /**
   * The fields in JSON format.
   */
  fieldsV1: Record<string, unknown>;

  /**
   * The name of the manager that manages these fields.
   */
  manager: string;

  /**
   * The operation type (e.g., "Apply", "Update").
   */
  operation: string;

  /**
   * The subresource name, if applicable.
   */
  subresource?: string;

  /**
   * The timestamp when the field was last modified.
   * Format: RFC3339 date-time string.
   */
  time: string;
}
